// <auto-generated />
using System;
using Barbearia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barbearia.Infrastructure.Migrations
{
    [DbContext(typeof(BarbeariaDbContext))]
    partial class BarbeariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Barbearia.Domain.Entities.Barbeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgendaAberta")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Barbeiros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgendaAberta = true,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@barbearia.com",
                            Nome = "Admin",
                            SenhaHash = "$2a$11$zSpNaUfBnGYJdqR5xSJTOeTLm3Mg5B7JOnBNRDJpHiHVnLaBOmT4a",
                            Telefone = "(11) 99999-0000"
                        });
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.BarbeiroServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroId")
                        .HasColumnType("int");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("BarbeiroId", "ServicoId")
                        .IsUnique();

                    b.ToTable("BarbeiroServicos");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.BloqueioAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId");

                    b.ToTable("BloquiosAgenda");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.HorarioBarbeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroId")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("AlmocoInicio")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("AlmocoFim")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId");

                    b.ToTable("HorariosBarbeiro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarbeiroId = 1,
                            DiaSemana = 1,
                            Disponivel = true,
                            HoraFim = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            IntervaloMinutos = 30
                        },
                        new
                        {
                            Id = 2,
                            BarbeiroId = 1,
                            DiaSemana = 2,
                            Disponivel = true,
                            HoraFim = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            IntervaloMinutos = 30
                        },
                        new
                        {
                            Id = 3,
                            BarbeiroId = 1,
                            DiaSemana = 3,
                            Disponivel = true,
                            HoraFim = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            IntervaloMinutos = 30
                        },
                        new
                        {
                            Id = 4,
                            BarbeiroId = 1,
                            DiaSemana = 4,
                            Disponivel = true,
                            HoraFim = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            IntervaloMinutos = 30
                        },
                        new
                        {
                            Id = 5,
                            BarbeiroId = 1,
                            DiaSemana = 5,
                            Disponivel = true,
                            HoraFim = new TimeSpan(0, 19, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            IntervaloMinutos = 30
                        },
                        new
                        {
                            Id = 6,
                            BarbeiroId = 1,
                            DiaSemana = 6,
                            Disponivel = true,
                            HoraFim = new TimeSpan(0, 16, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            IntervaloMinutos = 30
                        });
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroId")
                        .HasColumnType("int");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClienteTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoConfirmacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Corte masculino completo",
                            DuracaoMinutos = 30,
                            Nome = "Corte de Cabelo",
                            Preco = 45.00m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Aparação e modelagem de barba",
                            DuracaoMinutos = 20,
                            Nome = "Barba",
                            Preco = 30.00m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Corte completo + barba",
                            DuracaoMinutos = 50,
                            Nome = "Corte + Barba",
                            Preco = 65.00m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Design de sobrancelha masculina",
                            DuracaoMinutos = 15,
                            Nome = "Sobrancelha",
                            Preco = 15.00m
                        });
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.BarbeiroServico", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("BarbeiroServicos")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Barbearia.Domain.Entities.Servico", "Servico")
                        .WithMany("BarbeiroServicos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.BloqueioAgenda", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Bloqueios")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbeiro");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.HorarioBarbeiro", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Horarios")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbeiro");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Barbearia.Domain.Entities.Barbeiro", "Barbeiro")
                        .WithMany("Reservas")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Barbearia.Domain.Entities.Servico", "Servico")
                        .WithMany("Reservas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Barbeiro", b =>
                {
                    b.Navigation("BarbeiroServicos");

                    b.Navigation("Bloqueios");

                    b.Navigation("Horarios");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Barbearia.Domain.Entities.Servico", b =>
                {
                    b.Navigation("BarbeiroServicos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
